export enum ApiErrorType {
  APP_ID_NOT_EXIST = "APP_ID_NOT_EXIST",
  APP_ID_MISSING = "APP_ID_MISSING",
  PARAMS_NOT_VALID = "PARAMS_NOT_VALID",
  BODY_NOT_VALID = "BODY_NOT_VALID",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  PATH_NOT_FOUND = "PATH_NOT_FOUND",
  SERVER_ERROR = "SERVER_ERROR",
}

